### ISSUE TITLE
Make updates to `schema` repo automatically trigger deploy at `schemas.isotc211.org`

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas.isotc211.org#10]
1. When a push happens on https://github.com/ISO-TC211/schemas "master" branch, deploy  https://github.com/ISO-TC211/schemas.isotc211.org "production"

2. When a push happens on https://github.com/ISO-TC211/schemas "staging" branch, deploy  https://github.com/ISO-TC211/schemas.isotc211.org "staging"

cc @camobap795

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review:
 - https://github.com/ISO-TC211/schemas/pull/27
 - https://github.com/ISO-TC211/schemas.isotc211.org/pull/13

Please don't forget to add: `secrets.PAT_USERNAME`, `secrets.PAT_TOKEN` to https://github.com/ISO-TC211/schemas repo

**Comment by ronaldtse** [comment]
@CAMOBAP795 added both secrets.

**Comment by ronaldtse** [comment]
All done.
