### ISSUE TITLE
Page title shows `&nbsp;`

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/schemas.isotc211.org#7]
This is reported by @MatsAhlin , and I also noticed it too.

This comes from `_config.yml`.

![image001](https://user-images.githubusercontent.com/11865/54926719-d4a16800-4f4b-11e9-87e5-cd66ca62b83f.png)

@strogonoff why did we add the `&nbsp;& in the title? We need to fix this on all sites. Thanks.

**Comment by ronaldtse** [comment]
@MatsAhlin I think it's fixed. In FireFox I see this:

<img width="553" alt="Screen Shot 2019-03-25 at 10 43 43 PM" src="https://user-images.githubusercontent.com/11865/54928801-737b9380-4f4f-11e9-9849-82d5e516b96d.png">

**Comment by MatsAhlin** [comment]
Seems to be fixed when I looked in Chrome as well. Thanks.

**Comment by ronaldtse** [comment]
Thanks @MatsAhlin !
