### ISSUE TITLE
Add schema browser to schemas.isotc211.org

### ISSUE THREAD

**Issue by PeterParslow** [ISO-TC211/schemas.isotc211.org#8]
Looking good.

The default page at https://schemas.isotc211.org/ means I can no longer browse the available schemas, in the way I can at https://standards.iso.org/ittf/PubliclyAvailableStandards, which means I need to be well prepared before trying to find one.

Similarly, you can't browse to find parts or namespaces, e.g. https://schemas.isotc211.org/19110/ and https://schemas.isotc211.org/19110/fcc/ both give  404s.

For example, I just looked for 19139, forgetting it is -1 (even though I was the editor!) - and doesn't have a schema anyway.

Perhaps all this is deliberate, to ensure the schemas are only found by people coming from the (paid for) standards documents?

Also, the 404 isn't working "An Error Occurred While Attempting to Retrieve a Custom Error Document" 404.html

**Comment by strogonoff** [comment]
Moved under the schemas website repository, since the original request is about the schemas. This will be closed when https://github.com/ISO-TC211/jekyll-theme-isotc211/issues/6  is done.

**Comment by ronaldtse** [comment]
Cool, thanks for handling this @strogonoff !

**Comment by strogonoff** [comment]
@ronaldtse is there some shared traits among formats of different schemas?

E.g., [19115](https://github.com/ISO-TC211/schemas/blob/262a8c0f9eb252e1a66b4a9c666a034ff7bb5505/19115) and a few others (but not all of them) contain a “resources” subdirectory, which appears to provide some metadata.

**Comment by strogonoff** [comment]
First (imperfect) pass is live at https://schema.isotc211.org/, to be continued.

- Don’t forget to refresh browser cache to ensure updated stylesheets
- Per-filetype viewers may be implemented eventually, but there is a lot of unknowns here
- Since certain XML files are displayed as nothing by certain browsers, a download button may be added in near future

**Comment by ronaldtse** [comment]
@strogonoff this is an awesome start! Please continue with the issues mentioned 👍

**Comment by strogonoff** [comment]
Is there any metadata associated with each schema? https://schemas.isotc211.org/schemas/ is a bit bare with only numeric IDs, showing a title or brief summary could help I think.

It’d be great if we could somehow glean it from schema files, but I doubt it. Perhaps with TC 211 participation we could extend schema format to include a metadata file?

**Comment by ronaldtse** [comment]
@strogonoff the schemas are organized by ISO numbers, not sure if we could provide metadata for each. We could rely on Relaton to fetch the metadata of ISO documents, but they're still one step away from the schemas themselves.

But yes, I suppose we could supply extra information in a metadata file?

**Comment by strogonoff** [comment]
If there is a resource that can provide ISO/TC 211 schema metadata, given its ID, then sure plugin could query that resource during build.

Or I suppose the minimum metadata necessary to be bundled with schemas is a valid reference to an ISO document within each schema? Assuming each schema refers to a unique doc

**Comment by ronaldtse** [comment]
@PeterParslow forgot to let you know that the schema browser is now completed.

If you go to this page: https://schemas.isotc211.org/schemas/
<img width="736" alt="Screen Shot 2019-12-10 at 3 13 22 PM" src="https://user-images.githubusercontent.com/11865/70503966-9bec0200-1b5f-11ea-86ac-b431e8084def.png">

Click on any schema, and you will see the schema browser:
<img width="1042" alt="Screen Shot 2019-12-10 at 3 13 46 PM" src="https://user-images.githubusercontent.com/11865/70503994-aa3a1e00-1b5f-11ea-8e0f-79892448e539.png">

Closing this issue now -- for feedback and improvement suggestions, please file new issues. Thanks!

**Comment by PeterParslow** [comment]
OK - I'll open a new issue: this allows us to browse, but not in the way @jetgeo or I described - i.e. use a web browser to dereference URIs built on the expected pattern, in the way I can at https://standards.iso.org.

For example, I can't GET https://schemas.isotc211.org/schemas/19135/-2; I have to browse from the root, from https://schemas.isotc211.org/schemas/19135.

**Comment by ronaldtse** [comment]
@PeterParslow I see, you would like to still see the browser at: https://schemas.isotc211.org/schemas/19135/-2 . Correct?

**Comment by ronaldtse** [comment]
If so, we should be able to extend and handle that.

**Comment by PeterParslow** [comment]
That might solve it
